import { useState } from "react";
import { useI18n } from "../lib/i18n";
import { makeCrossNotation } from "../data/crossNotation";

export function CrossNotationCase() {
  const {t,locale}=useI18n();const [step,setStep]=useState(0);
  const changed=step>0,linked=step===2;
  const cases=[
    {id:"process",title:"BPMN",sub:t("Процесс заказа","Order process"),note:t("Вставить ожидание подтверждения перед отгрузкой.","Wait for confirmation before releasing the order.")},
    {id:"architecture",title:"C4",sub:t("Контейнеры приложения","Application containers"),note:t("Добавить приём события и обработку повторов.","Add event reception and duplicate handling.")},
    {id:"states",title:"UML · State",sub:t("Состояния Payment","Payment states"),note:t("Описать Pending, тайм-аут и поздний ответ.","Model Pending, timeouts and late responses.")},
    {id:"classes",title:"UML · Class",sub:t("Модель Payment","Payment model"),note:t("Проверить status и ключ обработанного события.","Review status and the processed-event key.")},
    {id:"requirements",title:t("Требования","Requirements"),sub:"REQ-17 / REQ-18",note:t("Уточнить критерии: отгрузка после подтверждения, эффект один раз.","Clarify acceptance: confirmed payment and one processing effect.")},
    {id:"risks",title:t("Карта рисков","Risk map"),sub:t("Сценарии отказа","Failure scenarios"),note:t("Проверить неоплаченную и повторную отгрузку; добавить тесты.","Review unpaid and duplicate shipments; add tests.")},
  ];
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(makeCrossNotation(locale),null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`plyra-cross-notation-${locale}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="cross-notation-case"><div className="case-heading"><span>{t("СЦЕНАРИЙ СЛЕДУЮЩЕГО ШАГА","NEXT-STEP DESIGN SCENARIO")}</span><h3>{t("Одна оплата — шесть моделей","One payment, six models")}</h3><p>{t("Провайдер начал подтверждать оплату отдельным событием, до 15 минут. В каких документах остались старые допущения?","The provider now confirms payments with a separate event, within 15 minutes. Which documents still contain the old assumptions?")}</p></div>
    <div className="case-steps" role="group" aria-label={t("Шаг примера","Scenario step")}>{[t("1. Разрозненные схемы","1. Separate diagrams"),t("2. Меняем контракт","2. Change the contract"),t("3. Видим последствия","3. Reveal impact")].map((label,i)=><button key={i} aria-pressed={step===i} onClick={()=>setStep(i)}>{label}</button>)}</div>
    <div className="case-models">{cases.map((item)=><section key={item.id} data-case-model={item.id} className={(linked?"needs-review ":"")+(changed&&item.id==="architecture"?"changed-model":"")}><header><b>{item.title}</b><span>{item.sub}</span>{changed&&item.id==="architecture"?<small>{t("изменён","changed")}</small>:linked?<small>{t("проверить","review")}</small>:null}</header><NotationFragment kind={item.id} changed={changed} linked={linked}/>{linked&&<p className="case-review">{item.note}</p>}</section>)}</div>
    <div className="case-explanation" role="status">{step===0?t("Каждый документ выглядит связно сам по себе. Общая карта соответствий пока отсутствует.","Each document is coherent on its own. There is no shared map of correspondences yet."):step===1?t("Обновили только интеграцию C4. Процесс и машина состояний по-прежнему считают ответ API успешной оплатой.","Only the C4 integration changed. The process and state machine still treat an API response as a successful payment."):t("Трассировка подсветила места для проверки. Правки в самих схемах согласует человек. Задача, сервис, состояние и требование сохраняют разные ID.","Trace links reveal what needs review. A person approves the diagram changes. Activity, service, state and requirement retain distinct IDs.")}</div>
    <p className="case-identity-note"><i className="line-sample line-identity"/>{t("Один ID: класс Payment в UML Class и контексте UML State; REQ-17 в процессе и требованиях.","Same ID: the Payment class in UML Class and the UML State context; REQ-17 in the process and requirements.")}</p>
    <button className="case-download" onClick={download}>{t("Скачать карту трассировки JSON","Download traceability map JSON")}</button><p className="case-scope">{t("Учебные фрагменты для обсуждения интерфейса. JSON открывается в нынешнем карточном виде Plyra; нативные редакторы BPMN, C4 и UML — следующий этап.","Teaching fragments for discussing the interface. JSON opens in Plyra’s current card view; native BPMN, C4 and UML renderers are a next step.")}</p>
  </section>;
}

function NotationFragment({kind,changed,linked}:{kind:string;changed:boolean;linked:boolean}) {
  const {t}=useI18n();const ink="#586374",gold="#9a6129",accent=linked?gold:ink;
  const marker=`case-arrow-${kind}`;
  const arrow=(x1:number,y1:number,x2:number,y2:number,dash?:string)=><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={ink} strokeWidth="1.3" strokeDasharray={dash} markerEnd={`url(#${marker})`}/>;
  const box=(x:number,y:number,w:number,h:number,label:string,fill="#fff",radius=7)=><g><rect x={x} y={y} width={w} height={h} rx={radius} fill={fill} stroke={accent} strokeWidth="1.2"/><text x={x+w/2} y={y+h/2+4} textAnchor="middle" fontSize="12" fill={ink}>{label}</text></g>;
  return <svg viewBox="0 0 420 190" role="img" aria-label={t(`Фрагмент модели ${kind}`,`${kind} model fragment`)}><defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 L10 5 L0 10Z" fill={ink}/></marker></defs>
    {kind==="process"&&<><circle cx="28" cy="87" r="12" fill="#fff" stroke={ink}/>{arrow(40,87,62,87)}{box(62,62,124,50,t("Запросить оплату","Request payment"))}{arrow(186,87,239,87)}{box(239,62,131,50,t("Отгрузить","Ship order"))}<text x="212" y="54" textAnchor="middle" fontSize="10" fill={accent}>{t("ответ API","API response")}</text><path d="M105 140H97V172H105" fill="none" stroke={gold}/><text x="111" y="159" fontSize="11" fill={gold}>REQ-17 · {t("после оплаты","after payment")}</text><line x1="184" y1="140" x2="271" y2="112" stroke={gold} strokeDasharray="2 4"/></>}
    {kind==="architecture"&&<><rect x="15" y="39" width="168" height="111" rx="5" fill="#366c94"/><text x="99" y="68" textAnchor="middle" fill="#fff" fontSize="14">Payment API</text><text x="99" y="91" textAnchor="middle" fill="#dbe9f4" fontSize="10">[Container · Python]</text><text x="99" y="119" textAnchor="middle" fill="#fff" fontSize="10">{t("Оркестрация оплаты","Payment orchestration")}</text><rect x="243" y="39" width="163" height="111" rx="5" fill={changed?"#ac7856":"#879099"}/><text x="324" y="72" textAnchor="middle" fill="#fff" fontSize="12">{t("Провайдер","Provider")}</text><text x="324" y="97" textAnchor="middle" fill="#fff" fontSize="9">[Software System]</text>{arrow(183,65,243,65)}<text x="212" y="53" textAnchor="middle" fontSize="9" fill={ink}>HTTPS</text>{arrow(243,126,183,126,changed?"4 4":undefined)}<text x="210" y="172" textAnchor="middle" fontSize="11" fill={changed?gold:ink}>{changed?t("Событие ≤ 15 минут","Event ≤ 15 minutes"):t("Результат в ответе","Result in response")}</text></>}
    {kind==="states"&&<><text x="19" y="29" fontSize="11" fill={gold}>Payment · {t("контекст: class.payment","context: class.payment")}</text><circle cx="35" cy="100" r="7" fill={ink}/>{arrow(42,100,63,100)}{box(63,75,102,49,"Created")}{arrow(165,100,270,100)}<text x="217" y="87" textAnchor="middle" fontSize="10" fill={accent}>API response</text>{box(270,75,110,49,"Paid")}{linked&&<text x="213" y="161" textAnchor="middle" fontSize="11" fill={gold}>{t("Где Pending и тайм-аут?","Where are Pending and timeout?")}</text>}</>}
    {kind==="classes"&&<><rect x="85" y="17" width="251" height="157" fill="#fff" stroke={accent}/><text x="210" y="40" textAnchor="middle" fontSize="13" fill={gold}>Payment · class.payment</text><line x1="85" y1="51" x2="336" y2="51" stroke={ink}/><text x="99" y="75" fontSize="12" fill={ink}>id: UUID</text><text x="99" y="97" fontSize="12" fill={accent}>status: Created | Paid</text><line x1="85" y1="111" x2="336" y2="111" stroke={ink}/><text x="99" y="135" fontSize="12" fill={ink}>confirm(): void</text><text x="99" y="157" fontSize="11" fill={ink}>release(): void</text></>}
    {kind==="requirements"&&<>{box(24,26,371,63,"",linked?"#fff9ed":"#fff",2)}<text x="38" y="49" fontSize="11" fill={gold}>«requirement» REQ-17</text><text x="38" y="72" fontSize="12" fill={ink}>{t("Отгрузка после успешной оплаты","Ship only after successful payment")}</text>{box(24,105,371,63,"",linked?"#fff9ed":"#fff",2)}<text x="38" y="128" fontSize="11" fill={gold}>«requirement» REQ-18</text><text x="38" y="150" fontSize="12" fill={ink}>{t("Бизнес-эффект — один раз","Apply the business effect once")}</text></>}
    {kind==="risks"&&<>{[0,1,2].flatMap(row=>[0,1,2].map(col=><rect key={`${row}-${col}`} x={107+col*61} y={16+row*44} width="59" height="42" fill={row+2-col<2?"#eecfcb":row+2-col<4?"#f2e2bf":"#e2eadf"}/>))}<circle cx="199" cy="80" r="9" fill={gold}/><text x="301" y="75" fontSize="10" fill={accent}>R-01</text><text x="301" y="92" fontSize="10" fill={ink}>{t("повтор","duplicate")}</text><text x="198" y="165" textAnchor="middle" fontSize="10" fill={ink}>{t("Последствия →","Impact →")}</text><text transform="translate(86 82) rotate(-90)" textAnchor="middle" fontSize="10" fill={ink}>{t("Вероятность →","Likelihood →")}</text></>}
  </svg>;
}
