import { useState } from "react";
import { useI18n } from "../lib/i18n";
import { generationExample, generationPrompt } from "../lib/generation";
import { HelpMedia } from "./HelpMedia";
import { CrossNotationCase } from "./CrossNotationCase";

function download(name:string,text:string,type="text/plain") {
  const url=URL.createObjectURL(new Blob([text],{type:`${type};charset=utf-8`}));
  const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function HelpView({page,onImport}:{page:"generate"|"faq";onImport:()=>void}) {
  const {t,locale}=useI18n();const [copied,setCopied]=useState(false),[fallback,setFallback]=useState(false);
  const prompt=generationPrompt(locale);
  const copy=async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);setFallback(false);}catch{download(`plyra-ai-prompt-${locale}.txt`,prompt);setFallback(true);}};
  const faq=[
    [t("Что делает «Оптимизировать расположение»?","What does Optimize layout do?"),t("Кнопка под холстом пробует расположить связанные ноды рядом, развести карточки и уменьшить пересечения и общие участки линий. Работает на Листе, в Развороте и на Одной плоскости. В Развороте учитываются все видимые слои, их связи и линии одного ID; на телефоне — открытый слой и боковые переходы. Результат вписывается в экран и сохраняется в JSON. «Отменить» возвращает всю расстановку одним действием; расчёт можно прервать. «Вписать» после оптимизации меняет масштаб, сохраняя позиции. Это приблизительный подбор, не гарантия отсутствия пересечений: для плотных видов оценка ограничена выборкой из 400 линий.","The button below the canvas tries nearby placements for connected nodes, separates cards, and reduces crossings and shared line segments. It works in Sheet, Spread and Flat view. A spread includes all visible layers, their connections and same-ID lines; on a phone it includes the open layer and side references. The result is fitted to the screen and saved in native JSON. Undo restores the entire arrangement in one step, and a calculation can be cancelled. After optimization, Fit changes the zoom while keeping positions. This is a heuristic, not a guarantee of a crossing-free drawing: dense views are evaluated using a sample of up to 400 lines.")],
    [t("Как различать три вида линий?","How do I distinguish the three line types?"),t("Тонкая сплошная стрелка — связь внутри слоя. Пунктирная стрелка — к сущности другого листа. Бронзово-золотая линия без стрелки — одна и та же сущность на нескольких листах, с одним ID и общим телом. Наведите на «Легенда линий» или нажмите её на телефоне.","A thin solid arrow is a relation within a layer. A dashed arrow connects to an entity on another sheet. An amber-bronze line without an arrow joins the same entity across sheets, sharing one ID and body. Hover over Line legend, or tap it on a phone.")],
    [t("С чего начать?","Where do I start?"),t("Выберите лист в верхней полосе. Стрелки и Alt+← / Alt+→ перелистывают карту. «＋ Добавить» создаёт узел на выбранном листе. Двойной клик по пустому месту делает то же на холсте.","Choose a sheet in the top strip. Use arrows or Alt+← / Alt+→ to turn pages. ＋ Add creates a node on the selected sheet. Double-click empty canvas space to create one there.")],
    [t("Что делает «+» на ноде?","What does + on a node do?"),t("Раскрывает редактор названия и тела прямо в карточке. Изменения общие для всех появлений этой сущности. «−» сворачивает редактор; «Отменить» возвращает правку.","It opens name and body fields inside the card. Edits are shared across every appearance of this entity. − collapses the editor; Undo reverts an edit.")],
    [t("Лист и слой — это одно и то же?","Are sheets and layers the same thing?"),t("Да. Лист — отдельная карта, слой — её представление в развороте или стопке. Цвет и название помогают узнавать её в любом режиме.","Yes. A sheet is one map; a layer is that sheet shown in a spread or stack. Its name and color remain consistent across views.")],
    [t("Что за полупрозрачные сущности за пунктиром?","What are the faded entities beyond the dashed line?"),t("Это ссылки на ноды других листов. Нажатие открывает лист с этой сущностью. Когда она уже видна на другом слое разворота, ссылка убирается, а линия идёт к самой ноде. За границей остаются только связи с листами вне текущего вида.","These are references to nodes on other sheets. Click one to open that entity’s sheet. If the entity is already visible in another spread layer, the reference is removed and the edge connects to the actual node. Only references outside the current view remain at the boundary.")],
    [t("Как собрать разворот?","How do I compose a spread?"),t("Выберите 2–6 слоёв и пропорции. В каждом заголовке «Слой:» можно выбрать другой лист. Три слоя — высокий слева; пять — широкий ряд посередине. Автоматическая раскладка подстраивается под место. После ручного перемещения или оптимизации позиции сохраняются, а «вписать» подбирает масштаб. Для новых пропорций можно снова оптимизировать расположение. «Боковые переходы» скрывает внешние карточки; тонкая рамка показывает активный слой.","Choose 2–6 layers and their proportions. Select a sheet in each Layer: header. Three layers have a tall left sheet; five have a wide middle row. Automatic layout adapts to the space. After a drag or optimization, positions are saved and Fit adjusts the zoom. Optimize again after changing proportions if needed. Side references hides external cards; a thin frame marks the active layer.")],
    [t("Почему на телефоне один лист?","Why is only one sheet shown on a phone?"),t("На узком экране разворот показывает активный лист, а полоса сверху позволяет быстро переключаться. Затухающие ссылки учитывают реально видимый лист. Стопку можно двигать одним пальцем и масштабировать двумя; её настройки сворачиваются.","On narrow screens, the spread shows its active sheet, with quick switching in the top strip. Faded references are computed for the sheet actually visible. Pan the stack with one finger and zoom with two; its settings can be collapsed.")],
    [t("Как читать стопку?","How do I read the stack?"),t("Галочками выберите слои. Настройте наклон, расстояние и масштаб. Тонкие сплошные стрелки — связи внутри слоя, пунктир — связи между слоями, бронзово-золотые линии — появления одного ID. Нажатие на ноду выделяет её связи. Подписи, связи и повторные появления переключаются отдельно. Начните с двух или трёх слоёв.","Select layers using checkboxes, then adjust tilt, spacing and scale. Thin solid arrows stay within a layer, dashed arrows connect layers, and amber-bronze lines join appearances of one ID. Selecting a node highlights its connections. Labels, edges and repeated appearances have separate switches. Start with two or three layers.")],
    [t("Как поместить одну сущность на несколько листов?","How can one entity appear on multiple sheets?"),t("Выберите ноду и в свойствах нажмите «+ ещё лист…». Это тот же ID и то же тело, с отдельными координатами на каждом листе. Новая связь между двумя нодами создаётся кнопкой «связать» и нажатием на вторую ноду.","Select a node and choose + another sheet… in its properties. It keeps the same ID and body, with a separate position on each sheet. To link two nodes, use Connect and then select the second node.")],
    [t("Нотация что-то удаляет?","Does a notation delete anything?"),t("Нет. Пресеты «процесс», «данные» и «аргументы» приглушают неподходящие типы и показывают счётчик исключённых узлов и связей. Это простые фильтры чтения. Лимит 15 — настраиваемая подсказка, а не доказанная граница восприятия.","No. Process, data and arguments presets dim excluded types and count the affected nodes and edges. These are simple reading filters. The default limit of 15 is an adjustable guideline, not a proven perceptual threshold.")],
    [t("Что проверяет lint?","What does lint check?"),t("Переполненные и пустые листы, отсутствующие концы связей, несвязанные ноды и подозрительные членства. Подсказка о втором листе — эвристика: смысл границы решает читатель. Корректность источников линт не проверяет.","It checks oversized or empty sheets, missing endpoints, isolated nodes and suspicious memberships. Suggestions to add a second sheet are heuristics; the reader decides whether the boundary makes sense. Lint does not verify source accuracy.")],
    [t("Как загрузить и сохранить карту?","How do I import and save a map?"),t("В меню «Ещё» доступны импорт JSON / двух CSV и экспорт. Plyra JSON сохраняет общие ID и членства. JSON Canvas создаёт отдельные карточки для появлений, а экспорт в дерево оставляет один основной лист, сохраняя рёбра. Для дальнейшего редактирования храните Plyra JSON. Формат для ИИ — в соседней вкладке.","More contains JSON / two-CSV import and export. Plyra JSON preserves shared IDs and memberships. JSON Canvas makes separate cards for appearances; tree export keeps one primary sheet and retains edges. Keep Plyra JSON for further editing. The AI format is in the adjacent tab.")],
    [t("Куда уходят данные и что переводится?","Where is data sent, and what is translated?"),t("Этот HTML работает без сервера и не отправляет карту в сеть. Автосохранение — в хранилище браузера, оно не заменяет скачанную резервную копию. RU/ENG переводит интерфейс и названия встроенных примеров. Ваши тексты и ID не переписываются; тела демонстрационных узлов остаются на исходном языке.","This HTML runs without a server and does not send the map over the network. Autosave uses browser storage; it does not replace a downloaded backup. RU/ENG translates the interface and built-in example names. Your prose and IDs are not rewritten; demo node bodies remain in their original language.")],
  ];
  return <article className="help-view" key={page}><div className="help-content">
    <p className="help-eyebrow">Plyra / {page==="generate"?"AI FORMAT":"FIELD GUIDE"}</p>
    <h2>{page==="generate"?t("Как сгенерировать готовый к загрузке документ?","How do I generate a file ready to import?"):t("FAQ / ЧАВО","FAQ")}</h2>
    {page==="generate"?<>
      <p className="help-lead">{t("Отдайте ИИ этот стандарт вместе со своими материалами. Результат — JSON-файл, который открывается в Plyra.","Give this standard and your source materials to an AI. The result is a JSON file that Plyra can open.")}</p>
      <HelpMedia topic="ai"/>
      <ol className="help-steps"><li>{t("Скопируйте стандарт","Copy the standard")}<span>{t("Добавьте вопрос и источники в конец запроса.","Append your question and sources to the prompt.")}</span></li><li>{t("Сохраните ответ как .json","Save the response as .json")}<span>{t("Без обёртки Markdown. Проверьте факты и источники.","No Markdown wrapper. Review the facts and sources.")}</span></li><li>{t("Загрузите и прочитайте","Import and review")}<span>{t("Plyra проверит структуру. Затем проверьте границы листов.","Plyra checks the structure. Then review sheet boundaries.")}</span></li></ol>
      <div className="help-actions"><button className="primary-button" onClick={()=>void copy()}>{t("Скопировать стандарт для ИИ","Copy AI standard")}</button><button onClick={()=>download(`plyra-example-${locale}.json`,JSON.stringify(generationExample(locale),null,2),"application/json")}>{t("Скачать пример JSON","Download example JSON")}</button><button onClick={onImport}>{t("Загрузить файл","Import a file")}</button></div>
      {(copied||fallback)&&<p role="status">{fallback?t("Буфер недоступен — стандарт скачан текстовым файлом.","Clipboard unavailable; the standard was downloaded as a text file."):t("Стандарт скопирован. Добавьте свои материалы перед отправкой ИИ.","Standard copied. Add your materials before sending it to an AI.")}</p>}
      <details open className="help-contract"><summary>{t("Стандарт Plyra v2 и полный пример","Plyra v2 contract and complete example")}</summary><pre>{prompt}</pre></details>
    </>:<><p className="help-lead">{t("Одна сущность. Несколько контекстов. Карта, которую можно читать по частям.","One entity. Several contexts. A map you can read one part at a time.")}</p><HelpMedia topic="lines"/><details className="help-media-extra"><summary>{t("Показать: редактирование через «+»","Show: editing with +")}</summary><HelpMedia topic="editing"/></details><details className="help-media-extra case-details"><summary>{t("Сквозной пример: BPMN, C4, UML, требования и риски","Cross-model example: BPMN, C4, UML, requirements and risks")}</summary><CrossNotationCase/></details><div className="faq-list">{faq.map(([question,answer],i)=><details key={i} open={i===0}><summary>{question}</summary><p>{answer}</p></details>)}</div></>}
  </div></article>;
}
