import { useState } from "react";
import { KINDS, type Graph, type TypeRegistry, type TypeDefinition, type Sheet, type AttributeDefinition } from "../model/types";
import { defaultTypes, readTypes, typesFor, typeUsage, sheetTypeId, SHAPES, NOTATION_IDS, DATA_TYPES } from "../lib/typeRegistry";
import { readAttributes } from "../lib/attributes";
import { uid } from "../lib/graph";
import { useTypes } from "../lib/TypeContext";
import { useI18n } from "../lib/i18n";
import { Modal } from "./Modal";

export const notationLabel=(id:string)=>({plyra:"Plyra",flowchart:"Flowchart",canvas:"Obsidian Canvas",bpmn:"BPMN",drawio:"draw.io"}[id]??id);
export const DATA_LABELS={text:["Текст","Text"],number:["Число","Number"],boolean:["Да / нет","Yes / no"],date:["Дата","Date"],url:["Ссылка","URL"],select:["Список вариантов","Choice"]} as const;
export function TagChoices({value,tags,onChange}:{value:string[];tags:TypeDefinition[];onChange:(ids:string[])=>void}){
  const {label}=useTypes();return <div className="tag-choices">{tags.map(tag=><label key={tag.id}><input type="checkbox" checked={value.includes(tag.id)} onChange={e=>onChange(e.target.checked?[...value,tag.id]:value.filter(id=>id!==tag.id))}/><i style={{background:tag.color}}/>{label(tag)}</label>)}</div>;
}
export function TypeManager({graph,onSave,onClose,initialTab="sheets"}:{graph:Graph;onSave:(types:TypeRegistry,sheets:Sheet[])=>void;onClose:()=>void;initialTab?:"sheets"|"nodes"|"edges"|"attributes"}){
  const {t}=useI18n(),{label}=useTypes();
  const [draft,setDraft]=useState(()=>typesFor(graph));
  const [sheets,setSheets]=useState(()=>graph.sheets.map(s=>({...s,typeId:sheetTypeId(s,typesFor(graph)),tags:s.tags??[]})));
  const [tab,setTab]=useState(initialTab),[selected,setSelected]=useState(()=>typesFor(graph)[initialTab][0]?.id??"");
  const [activeTag,setActiveTag]=useState<string|null>(null),[activeType,setActiveType]=useState<string|null>(null),[activeSheet,setActiveSheet]=useState(graph.sheets[0]?.id??"");
  const [error,setError]=useState("");const base=defaultTypes();
  const current={...graph,types:draft,sheets};
  const change=(category:keyof TypeRegistry,id:string,patch:Record<string,unknown>)=>setDraft(d=>({...d,[category]:d[category].map(x=>x.id===id?{...x,...patch}:x)}));
  const add=(category:keyof TypeRegistry)=>{
    if(draft[category].length>=200)return;
    const id=uid("user:"),common={id,label:t(category==="tags"?"Новый тег":category==="attributes"?"Новый атрибут":"Новый тип",category==="tags"?"New tag":category==="attributes"?"New attribute":"New type")};
    const item=category==="attributes"?{...common,dataType:"text"}:category==="nodes"?{...common,color:"#475569",base:"entity",notation:"plyra"}:{...common,color:category==="edges"?"#475569":"#2563eb"};
    setDraft(d=>({...d,[category]:[...d[category],item]} as TypeRegistry));
    if(category==="tags")setActiveTag(id);else if(category==="sheets")setActiveType(id);else setSelected(id);setError("");
  };
  const remove=(category:keyof TypeRegistry,id:string)=>setDraft(d=>({...d,[category]:d[category].filter(x=>x.id!==id)}));
  const editor=(category:keyof TypeRegistry,id:string)=>{
    const item=draft[category].find(x=>x.id===id);if(!item)return null;
    const used=typeUsage(current,category,id),builtin=category!=="tags"&&category!=="attributes"&&base[category].some(x=>x.id===id);
    return <div className="type-editor" key={id}>
      <label htmlFor="type-label">{t("Название","Name")}</label><input id="type-label" maxLength={80} value={item.label} onChange={e=>change(category,id,{label:e.target.value})}/>
      <label htmlFor="type-label-en">{t("Название на английском (необязательно)","English name (optional)")}</label><input id="type-label-en" maxLength={80} value={item.labelEn??""} onChange={e=>change(category,id,{labelEn:e.target.value})}/>
      <label htmlFor="type-description">{t("Описание","Description")}</label><textarea id="type-description" rows={2} maxLength={2000} value={item.description??""} onChange={e=>change(category,id,{description:e.target.value})}/>
      {'color' in item&&category!=="edges"&&<><label htmlFor="type-color">{t("Цвет","Color")}</label><input id="type-color" type="color" value={item.color} onChange={e=>change(category,id,{color:e.target.value})}/></>}
      {category==="nodes"&&'base' in item&&<><label htmlFor="type-notation">{t("Нотация типа","Type notation")}</label><select id="type-notation" value={item.notation??"plyra"} onChange={e=>change(category,id,{notation:e.target.value})}>{NOTATION_IDS.map(n=><option key={n} value={n}>{notationLabel(n)}</option>)}</select><label htmlFor="type-base">{t("Базовый тип Plyra","Plyra base type")}</label><select id="type-base" value={item.base} onChange={e=>change(category,id,{base:e.target.value})}>{KINDS.map(k=><option key={k.id} value={k.id}>{t(k.label)}</option>)}</select><label htmlFor="type-shape">{t("Форма узла","Node shape")}</label><select id="type-shape" value={item.shape??""} onChange={e=>change(category,id,{shape:e.target.value||undefined})}><option value="">{t("По базовому типу","From base type")}</option>{SHAPES.map(s=><option key={s} value={s}>{t(s, s)}</option>)}</select><p className="field-help">{t("Нотация задаёт знакомый набор типов и форм. Импортированные узлы сохраняют размеры и расположение на своём листе.","A notation supplies familiar types and shapes. Imported nodes keep their size and position on each sheet.")}</p></>}
      {category==="edges"&&<p className="field-help">{t("Тип описывает смысл связи. Сплошная линия — на одном листе, пунктир — между листами. Один ID отмечается золотым.","A type describes the relation. Solid lines stay on a sheet; dashed lines cross sheets. Gold marks the same ID.")}</p>}
      {category==="attributes"&&'dataType' in item&&<><label htmlFor="attribute-data-type">{t("Тип данных","Data type")}</label><select id="attribute-data-type" disabled={used>0} value={item.dataType} onChange={e=>change(category,id,{dataType:e.target.value,options:e.target.value==="select"?[t("Вариант 1","Option 1")]:undefined})}>{DATA_TYPES.map(k=><option key={k} value={k}>{t(DATA_LABELS[k][0],DATA_LABELS[k][1])}</option>)}</select>{used>0&&<p className="field-help">{t("Тип данных закреплён, пока атрибут используется в узлах.","The data type is fixed while nodes use this attribute.")}</p>}{item.dataType==="select"&&<><label htmlFor="attribute-options">{t("Варианты — по одному в строке","Options — one per line")}</label><textarea id="attribute-options" rows={4} value={item.options?.join("\n")??""} onChange={e=>change(category,id,{options:e.target.value.split("\n")})}/></>}</>}
      <div className="type-id">ID: {id} · {t("Использований","Used")}: {used}</div><button className="danger" disabled={builtin||used>0} onClick={()=>remove(category,id)}>{t("Удалить","Delete")}</button>
    </div>;
  };
  return <Modal title={t("Типы проекта","Project types")} onClose={onClose} wide>
    <div className="type-tabs" role="tablist" aria-label={t("Словари типов","Type dictionaries")}>{([['sheets','Листы','Sheets'],['nodes','Узлы','Nodes'],['edges','Связи','Relations'],['attributes','Атрибуты','Attributes']] as const).map(([id,ru,en])=><button key={id} role="tab" id={`type-tab-${id}`} aria-controls="type-panel" aria-selected={tab===id} onClick={()=>{setTab(id);setSelected(draft[id][0]?.id??"");setActiveTag(null);setActiveType(null);setError("");}}>{t(ru,en)}</button>)}</div>
    <div role="tabpanel" id="type-panel" aria-labelledby={`type-tab-${tab}`}>
      {tab==="sheets"?<div className="sheet-catalog">
        <section data-catalog="tags"><header><h3>{t("Теги листов","Sheet tags")} <small>{draft.tags.length}</small></h3><button disabled={draft.tags.length>=200} onClick={()=>{setActiveType(null);add("tags");}}>{t("+ Добавить тег","+ Add tag")}</button></header><div className="catalog-chips">{draft.tags.map(tag=><button key={tag.id} aria-pressed={activeTag===tag.id} onClick={()=>{setActiveTag(activeTag===tag.id?null:tag.id);setActiveType(null);}}><i style={{background:tag.color}}/>{label(tag)}</button>)}</div>{activeTag&&editor("tags",activeTag)}</section>
        <section data-catalog="sheet-types"><header><h3>{t("Типы листов","Sheet types")} <small>{draft.sheets.length}</small></h3><button disabled={draft.sheets.length>=200} onClick={()=>{setActiveTag(null);add("sheets");}}>{t("+ Добавить тип","+ Add type")}</button></header><div className="catalog-chips">{draft.sheets.map(item=><button key={item.id} aria-pressed={activeType===item.id} onClick={()=>{setActiveType(activeType===item.id?null:item.id);setActiveTag(null);}}><i style={{background:item.color}}/>{label(item)}</button>)}</div>{activeType&&editor("sheets",activeType)}</section>
        <section data-catalog="sheets"><header><h3>{t("Листы проекта","Project sheets")} <small>{sheets.length}</small></h3><button disabled={sheets.length>=100} onClick={()=>{const id=uid("s_");setSheets(all=>[...all,{id,name:t("Новый лист","New sheet"),notation:"plyra",typeId:"свободная",tags:[],color:draft.sheets[0].color,layout:"manual",limit:15}]);setActiveSheet(id);}}>{t("+ Добавить лист","+ Add sheet")}</button></header>
          <p className="field-help">{t("У каждого листа один тип и несколько тегов.","Each sheet has one type and multiple tags.")}</p>
          {sheets.map(s=><div className="catalog-sheet" key={s.id}><button className="catalog-sheet-heading" aria-expanded={activeSheet===s.id} onClick={()=>setActiveSheet(activeSheet===s.id?"":s.id)}><i style={{background:s.color}}/><b>{s.name}</b><span>{label(draft.sheets.find(x=>x.id===s.typeId)??draft.sheets[0])}</span><small>{s.tags.map(id=>label(draft.tags.find(x=>x.id===id)!)).join(" · ")}</small></button>{activeSheet===s.id&&<div className="catalog-sheet-editor"><label htmlFor="catalog-sheet-name">{t("Название листа","Sheet name")}</label><input id="catalog-sheet-name" maxLength={80} value={s.name} onChange={e=>setSheets(all=>all.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/><label htmlFor="catalog-sheet-type">{t("Тип листа","Sheet type")}</label><select id="catalog-sheet-type" value={s.typeId} onChange={e=>setSheets(all=>all.map(x=>x.id===s.id?{...x,typeId:e.target.value}:x))}>{draft.sheets.map(d=><option key={d.id} value={d.id}>{label(d)}</option>)}</select><fieldset><legend>{t("Теги листа","Sheet tags")}</legend><TagChoices tags={draft.tags} value={s.tags} onChange={tags=>setSheets(all=>all.map(x=>x.id===s.id?{...x,tags}:x))}/></fieldset><button className="danger" disabled={sheets.length<2||graph.nodes.some(n=>n.sheets.includes(s.id))} onClick={()=>setSheets(all=>all.filter(x=>x.id!==s.id))}>{t("Удалить пустой лист","Delete empty sheet")}</button></div>}</div>)}
        </section>
      </div>:<div className="type-workspace"><div className="type-list"><button className="primary" disabled={draft[tab].length>=200} onClick={()=>add(tab)}>{tab==="attributes"?t("+ Создать атрибут","+ Create attribute"):t("+ Создать тип","+ Create type")}</button>{draft[tab].map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><span>{label(item)}</span>{'notation' in item&&<small>{notationLabel(String(item.notation))}</small>}{'dataType' in item&&<small>{t(DATA_LABELS[(item as AttributeDefinition).dataType][0],DATA_LABELS[(item as AttributeDefinition).dataType][1])}</small>}</button>)}</div>{editor(tab,selected)??<p className="modal-intro">{t("Создайте запись в справочнике, затем добавьте её к узлам.","Create a definition, then add it to nodes.")}</p>}</div>}
    </div>
    {error&&<p role="alert" className="form-error">{error}</p>}
    <footer><button onClick={onClose}>{t("Отмена","Cancel")}</button><button className="primary" onClick={()=>{try{const checked=readTypes(draft);if(sheets.some(s=>!s.name.trim()||!checked.sheets.some(d=>d.id===s.typeId)||s.tags.some(id=>!checked.tags.some(d=>d.id===id))))throw new Error(t("Проверьте названия, типы и теги листов.","Check sheet names, types and tags."));for(const n of graph.nodes)readAttributes(n.attributes,checked);onSave(checked,sheets.map(s=>({...s,name:s.name.trim()})));}catch(e){setError((e as Error).message);}}}>{t("Сохранить типы","Save types")}</button></footer>
  </Modal>;
}
