import { useI18n } from "../lib/i18n";
import { useTypes } from "../lib/TypeContext";
import { Modal } from "./Modal";
interface Props {hybrid:boolean;setHybrid:(v:boolean)=>void;body:boolean;setBody:(v:boolean)=>void;external:boolean;setExternal:(v:boolean)=>void;hiddenNodes:Set<string>;hiddenEdges:Set<string>;setHiddenNodes:(s:Set<string>)=>void;setHiddenEdges:(s:Set<string>)=>void;onClose:()=>void}
export function VisibilityDialog(p:Props){
  const {t}=useI18n(),{nodeTypes,edgeTypes,label}=useTypes();
  const toggle=(old:Set<string>,id:string)=>{const next=new Set(old);if(next.has(id))next.delete(id);else next.add(id);return next;};
  return <Modal title={t("Показ на экране","Display settings")} onClose={p.onClose} wide>
    <p className="modal-intro">{t("Эти настройки меняют вид схемы. Они не удаляют данные и не меняют экспорт .plyra или draw.io.","These settings change the view. They do not delete data or change .plyra or draw.io exports.")}</p>
    <div className="visibility-grid"><section><h3>{t("На листах и в развороте","Sheets and spreads")}</h3>
      <label className="check-row"><input type="checkbox" checked={p.hybrid} onChange={e=>p.setHybrid(e.target.checked)}/>{t("Форма карточек Plyra по типу","Plyra card shapes by type")}</label><p className="field-help">{t("Выключите, чтобы карточки Plyra имели одинаковую форму. Фигуры нотаций сохраняют свою геометрию.","Turn off for uniform Plyra cards. Notation shapes keep their geometry.")}</p>
      <label className="check-row"><input type="checkbox" checked={p.body} onChange={e=>p.setBody(e.target.checked)}/>{t("Описания и атрибуты узлов","Node descriptions and attributes")}</label>
      <label className="check-row"><input type="checkbox" checked={p.external} onChange={e=>p.setExternal(e.target.checked)}/>{t("Карточки со ссылками за границей листа","Reference cards outside the sheet")}</label><p className="field-help">{t("Это узлы с других листов, связанные с текущим. Нажатие открывает исходный лист. Выключение убирает эти карточки с одиночного листа; в развороте — карточки узлов с неоткрытых листов. Линии между открытыми листами настраиваются в самом развороте.","These are related nodes from other sheets. Click to open their source sheet. Turning this off hides these cards on a single sheet, and references to unopened sheets in a spread. Lines between open sheets have separate controls in the spread.")}</p>
      <p className="field-help identity-help">{t("Золотая линия «один ID» означает один общий узел на разных листах. Фиолетовая — связь между разными узлами. Их видимость отдельно настраивается в обзоре листов, развороте и стопке.","A gold 'same ID' line marks one shared node on different sheets. Purple connects distinct nodes. The sheet overview, Spread and Stack have separate visibility controls for these lines.")}</p>
    </section><section><h3>{t("Типы узлов","Node types")}</h3><div className="filter-bulk-actions" data-filter-actions="nodes"><button type="button" aria-label={t("Выбрать все типы узлов","Select all node types")} onClick={()=>p.setHiddenNodes(new Set())}>{t("Выбрать все","Select all")}</button><button type="button" aria-label={t("Выключить все типы узлов","Turn off all node types")} onClick={()=>p.setHiddenNodes(new Set(nodeTypes.map(k=>k.id)))}>{t("Выключить все","Turn off all")}</button></div><p className="field-help">{t("Уберите отметку, чтобы приглушить карточки типа и их линии. Фильтр применяется к листам; оглавление показывает структуру листов целиком.","Uncheck to dim a node type and its lines on sheets. Contents still shows the complete sheet structure.")}</p><div className="filter-checks">{nodeTypes.map(k=><label className="check-row" key={k.id} title={k.description}><input type="checkbox" checked={!p.hiddenNodes.has(k.id)} onChange={()=>p.setHiddenNodes(toggle(p.hiddenNodes,k.id))}/><span>{label(k)}</span></label>)}</div>
      <h3>{t("Типы связей","Relation types")}</h3><div className="filter-bulk-actions" data-filter-actions="edges"><button type="button" aria-label={t("Выбрать все типы связей","Select all relation types")} onClick={()=>p.setHiddenEdges(new Set())}>{t("Выбрать все","Select all")}</button><button type="button" aria-label={t("Выключить все типы связей","Turn off all relation types")} onClick={()=>p.setHiddenEdges(new Set(edgeTypes.map(k=>k.id)))}>{t("Выключить все","Turn off all")}</button></div><p className="field-help">{t("Уберите отметку, чтобы приглушить линии этого типа во всех видах. Линии остаются на месте. Общие узлы с одним ID не являются связями. «Выключить все» снимает все отметки и приглушает объекты; данные сохраняются.","Uncheck to dim this relation type in every view. Lines keep their positions. Shared nodes with one ID are not relations. Turn off all unchecks and dims objects while preserving the data.")}</p><div className="filter-checks">{edgeTypes.map(k=><label className="check-row" key={k.id} title={k.description}><input type="checkbox" checked={!p.hiddenEdges.has(k.id)} onChange={()=>p.setHiddenEdges(toggle(p.hiddenEdges,k.id))}/><span style={{color:k.color}}>↗</span> {label(k)}</label>)}</div>
    </section></div><footer><button onClick={()=>{p.setHiddenNodes(new Set());p.setHiddenEdges(new Set());}}>{t("Показать все типы","Show all types")}</button><button className="primary" onClick={p.onClose}>{t("Готово","Done")}</button></footer>
  </Modal>;
}
